E_Auction_Website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Auction_Website.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

E_Auction_Website/Controllers/WebsiteController.cs
using E_Auction_Website.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Auction_Website.Controllers
{
    public class WebsiteController : Controller
    {
        public const String USER = "user";

        AuctionDBEntities db = new AuctionDBEntities();

        // GET: Website
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            if(Session[USER]!=null)
            {
                var user = (User)Session[USER];
                return RedirectToAction("Home", new { user = user });

            }
            return View();
        }

        [HttpPost]
        public ActionResult Login(String Login,String Password)
        {
            var user = db.Users.Where(x => x.Login.Equals(Login) && x.Password.Equals(Password)).SingleOrDefault();

            if (user != null)
            {
                Session[USER] = user;

                return RedirectToAction("Home", new { user = user });
            }

            return View(new { Message = "Incorrect Login" });
        }

        public ActionResult Home(User user)
        {
            return View(user);
        }

        public ActionResult Logout()
        {
            Session.Clear();

            return RedirectToAction("Login");
        }

        public ActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Signup(String Username,long Tel,String Login,String Password)
        {
            var user = new User(Username, Password, Login, Tel);

            db.Users.Add(user);

            db.SaveChanges();

            return RedirectToAction("Login");
        }

        [HttpPost]
        public ActionResult AddProduct(String ProductName,int UserID,decimal InitialPrice)
        {
            var product = new Product(UserID, ProductName, InitialPrice, false);

            db.Products.Add(product);

            db.SaveChanges();

            return RedirectToAction("MyProducts", new { UserID = UserID });
        }

        public ActionResult AddProduct()
        {
            return View();
        }

        public ActionResult MyProducts(int UserID)
        {
            var products = db.Products.Where(x => x.UserID == UserID).ToList();

            return View(products);
        }

        public ActionResult MyProductDetails(int ProductID)
        {
            var p = db.Products.Find(ProductID);
            var product = new Product(p, p.BidOffers.ToList());

            return View(product);
        }

        public ActionResult SoldProduct(int ProductID)
        {
            var product = db.Products.Find(ProductID);
            product.IsSold = true;
            db.SaveChanges();

            return RedirectToAction("MyProductDetails", new { ProductID = ProductID });
        }

        [HttpGet]
        public ActionResult OthersProducts(int UserID)
        {
            var products = db.Products.Where(x => x.UserID != UserID && !x.IsSold).ToList();

            return View(products);
        }

        public ActionResult OtherProductDetails(int ProductID)
        {
            var product = db.Products.Find(ProductID);

            decimal maxBid=product.InitialPrice;
            if (product.BidOffers.Count>0)
                maxBid = product.BidOffers.Max(x => x.OfferedPrice);

            ViewBag.MaxBid = maxBid;

            return View(product);

        }


        //Search
        [HttpPost]
        public ActionResult OthersProducts(String ProductName,int UserID)
        {
            var products = db.Products.Where(x => x.UserID != UserID && x.ProductName.Contains(ProductName)).ToList();

            return View(products);
        }

        public ActionResult BidProduct(int UserID,int ProductID,decimal OfferedPrice)
        {
            var product = db.Products.Find(ProductID);

            var maxBid = product.InitialPrice;
            if(product.BidOffers.Count>0)
                maxBid = product.BidOffers.Max(x => x.OfferedPrice);

            if (OfferedPrice < maxBid)
            {
                ViewBag.Message = "Offered Price is less than max bid";
                return RedirectToAction("OtherProductDetails", new { ProductID = ProductID });
            }
            else
            {
                var bidOffer = new BidOffer(UserID, ProductID, OfferedPrice);
                db.BidOffers.Add(bidOffer);
                db.SaveChanges();

                return RedirectToAction("OtherProductDetails", new { ProductID = ProductID });
            }


        }
    }
}

E_Auction_Website/Views/Website/AddProduct.cshtml
@using E_Auction_Website.Controllers
@using E_Auction_Website.Models
@model E_Auction_Website.Models.User

@{
    ViewBag.Title = "New User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-danger">Product Information</h2>

<div>
    @if (Session[WebsiteController.USER] == null)
    {
        Response.Redirect("Login");
    }
    <hr />
    @using (Html.BeginForm("AddProduct", "Website", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <table class="table">

            <tr>
                @{
                    var user = (User)Session[WebsiteController.USER];
                }
                <td>    User ID   </td>
                <td> <input type="number" name="UserID" value="@user.UserID" class="form-control" required readonly/></td>

            </tr>

            <tr>
                <td> Product Name</td>
                <td> <input type="text" name="ProductName" class="form-control" required autofocus /></td>

            </tr>
            <tr>
                <td>Initial Price </td>
                <td> <input type="number" name="InitialPrice" class="form-control" required /></td>

            </tr>
         
          

            <tr>
                <td></td>
                <td>
                    <input type="submit" class="btn btn-block btn-danger text-info text-center" value="Ok" />
                </td>
            </tr>
        </table>
    }
</div>
<p>
    @if (ViewBag.Message != null)
    {
        <h2 class="bg-warning text-danger">
            @ViewBag.Message
        </h2>
    }
</p>

E_Auction_Website/Views/Website/Home.cshtml
@using E_Auction_Website.Models
@using E_Auction_Website.Controllers
@{
    ViewBag.Title = "Main";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <header>
        <img src="~/Pictures/e_auction.jpeg" class="img-responsive">


    </header>
    @if (Session[WebsiteController.USER] == null)
    {
        Response.Redirect("Login");
    }
    
        <div>
            <h2></h2>

            <div>
                @{
                    var user = (User)Session[WebsiteController.USER];
                }
                @Html.ActionLink("My Products", "MyProducts", "Website", new { UserID = user.UserID }, new { @class = "btn btn-danger btn-lg btn-block" })
                @Html.ActionLink("Offered Products", "OthersProducts", "Website", new { UserID = user.UserID }, new { @class = "btn btn-danger btn-lg btn-block" })
            </div>
        </div>
  

</div>

E_Auction_Website/Views/Website/Login.cshtml
@using E_Auction_Website.Controllers
@{
    ViewBag.Title = "Home Page";
}
@{if (Session[WebsiteController.USER] != null)
    {
            Response.Redirect("Home");
    }
}
<div class="w3-card-4">

    @using (Html.BeginForm("Login", "Website", FormMethod.Post, new { @class = "w3-container" }))
    {
 <!--   <form class="w3-container" method="post" action="Index">-->
        <p>
            <label class="w3-text-brown"><b>Login</b></label>
            <input class="w3-input w3-border w3-sand" name="Login" type="text" required autofocus>
        </p>
        <p>
            <label class="w3-text-brown"><b>Password</b></label>
            <input class="w3-input w3-border w3-sand" name="Password" type="password" required>
        </p>
        <p>
            <button class="btn btn-primary btn-lg btn-block" >Login</button>
        </p>
    }

    <p>
        @Html.ActionLink("Create Account", "Signup", "Website", null, new { @class = "btn btn-primary btn-lg btn-block" })
    </p>
</div>

E_Auction_Website/Views/Website/MyProductDetails.cshtml
@using E_Auction_Website.Controllers
@using E_Auction_Website.Models
@model E_Auction_Website.Models.Product

@{
    ViewBag.Title = "MyProductDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-danger">@Model.ProductName Details</h2>

<div>
    @if (Session[WebsiteController.USER] == null)
    {
        Response.Redirect("Login");
    }
    <hr />
    <dl class="dl-horizontal table">
      

        <dt style="text-align:left">
            @Html.DisplayNameFor(model => model.InitialPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InitialPrice)
        </dd>


    </dl>


    @{
        if (Model.IsSold)
        {
            <img src="~/Pictures/sold.png" width="60" height="60" style="text-align:center;margin:0 auto" />
        }
        else
        {
            <img src="~/Pictures/unsold.png" width="60" height="60" style="text-align:center;margin:0 auto"/>
        }
    }

    @if (Model.BidOffers.Count > 0)
    {
    <table class="table table-dark">
        <tr><td>Username</td><td>Offered Price</td></tr>

        @{
            var bidOffers = Model.BidOffers;
            foreach (BidOffer bo in bidOffers)
            {
                <tr>
                    <td style="text-align:left">
                        @bo.Username
                    </td>
                    <td>
                        @bo.OfferedPrice
                    </td>
                </tr>
            }
        }
    </table>
            }
</div>
<p>
    @Html.ActionLink("Set Sold", "SoldProduct", new { ProductID = Model.ProductID },new { @class = "btn btn-block btn-danger text-info text-center" }) |
    @Html.ActionLink("Back to List", "MyProducts",new { UserID=Model.UserID})
</p>

E_Auction_Website/Views/Website/MyProducts.cshtml
@using E_Auction_Website.Models
@using E_Auction_Website.Controllers
@model IEnumerable<E_Auction_Website.Models.Product>

@{
    ViewBag.Title = "MyProducts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-danger">My Products</h2>

@if (Session[WebsiteController.USER] == null)
{
    Response.Redirect("Login");
}
<table class="table  table-dark ">
    <tr>
        <th>
            Product
        </th>
        <th>
            Initial Price
        </th>
        <th>
            Is Sold ?
        </th>
    
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InitialPrice)
        </td>
        <td>
          @{ 
              if (item.IsSold)
              {
                  <img src="~/Pictures/sold.png" width="35" height="35" />
              }
              else
              {
                <img src="~/Pictures/unsold.png" width="35" height="35" />
              }
        }
        </td>
      
        <td>
            @Html.ActionLink("Details", "MyProductDetails", new { ProductID=item.ProductID }) 
        </td>
    </tr>
}

</table>
@{
    var user = (User)Session[WebsiteController.USER];
}
@Html.ActionLink("New Product", "AddProduct", "Website", null, new { @class = "btn btn-danger btn-lg btn-block" })

E_Auction_Website/Views/Website/OtherProductDetails.cshtml
@using E_Auction_Website.Controllers
@using E_Auction_Website.Models
@model E_Auction_Website.Models.Product

@{
    ViewBag.Title = "OtherProductDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.ProductName Details</h2>
<style>
    dl dt{
        float:left;
        text-align:left;
    }
</style>
<div>
    @if (Session[WebsiteController.USER] == null)
    {
        Response.Redirect("Login");
    }
    @{
        var user = (User)Session[WebsiteController.USER];
    }

    <hr />
    <dl class="table table-dark">

 

        <dt style="text-align:left">
           Initial Price
        </dt>

        <dd style="text-align:right">
            @Html.DisplayFor(model => model.InitialPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Username)
        </dt>

        <dd style="text-align:right">
            @Html.DisplayFor(model => model.User.Username)
        </dd>


        <dt>
            Highest Bid
        </dt>

        <dd style="text-align:right">
            @ViewBag.MaxBid
        </dd>

        <dt>
            Your  Bid
        </dt>
@using (Html.BeginForm("BidProduct", "Website", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        <dd>
            <input type="number" name="OfferedPrice" class="form-control" required autofocus />
        </dd>

        <dt>
            Product ID
        </dt>
        <dd>
            <input type="number" name="ProductID" class="form-control" value="@Model.ProductID" readonly/>
        </dd>

        <dt>
            User ID
        </dt>
        <dd>
            
            <input type="number" name="UserID" class="form-control" value="@user.UserID" readonly/>
        </dd>

        <dt>

        </dt>

        <dd>
                <input type="submit" class="btn btn-block btn-danger text-info text-center" value="Ok" />
           
        </dd>
}

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "OthersProducts", new { UserID = user.UserID })
</p>

E_Auction_Website/Views/Website/OthersProducts.cshtml
@using E_Auction_Website.Controllers
@using E_Auction_Website.Models
@model IEnumerable<E_Auction_Website.Models.Product>

@{
    ViewBag.Title = "OthersProducts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-danger">Offered Products</h2>


@if (Session[WebsiteController.USER] == null)
{
    Response.Redirect("Login");
}
@{
    var user = (User)Session[WebsiteController.USER];
}
@using (Html.BeginForm("OthersProducts", "Website", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table class="table table-dark" >
        <tr>
            <td>
                <input type="text" class="form-control" width="60%"  placeholder="product name..." name="ProductName" />
            </td>

            <td>
                <input type="text" class="form-control" width="10%"  value="@user.UserID" name="UserID" readonly/>
            </td>

            <td>
                <input type="submit" class="form-control" width="30%"  value="Search" name="btnSearch" />
            </td>
        </tr>
    </table>
    

}
<table class="table table-dark">
    <tr>
        <th>
            Product
        </th>
        <th>
           Initial Price
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Username)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InitialPrice)
        </td>
   
        <td>
            @Html.DisplayFor(modelItem => item.User.Username)
        </td>
        <td>
            @Html.ActionLink("Details", "OtherProductDetails", new { ProductID=item.ProductID }) 
        </td>
    </tr>
}

</table>

E_Auction_Website/Views/Website/Signup.cshtml
@model E_Auction_Website.Models.User

@{
    ViewBag.Title = "New User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-danger">Customer Information</h2>

<div>
    <hr />
    @using (Html.BeginForm("Signup", "Website", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <table class="table table-dark">
            <tr>
                <td> Username</td>
                <td> <input type="text" name="Username" class="form-control" required autofocus /></td>

            </tr>
            <tr>
                <td>Tel </td>
                <td> <input type="number" name="Tel" class="form-control" required /></td>

            </tr>
            <tr>
                <td>      Login </td>
                <td> <input type="text" name="Login" class="form-control" required /></td>

            </tr>
            <tr>
                <td>    Password </td>
                <td><input type="text" name="Password" required class="form-control" /></td>

            </tr>
            
            <tr>
                <td></td>
                <td>
                    <input type="submit" class="btn btn-block btn-danger text-info text-center" value="Ok" />
                </td>
            </tr>
        </table>
    }


    <p>
        @Html.ActionLink("Login", "Login", "Website", null, new { @class = "btn btn-primary btn-lg btn-block" })
    </p>
</div>
<p>
    @if (ViewBag.Message != null)
    {
        <h2 class="bg-warning text-danger">
            @ViewBag.Message
        </h2>
    }
</p>